version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: previred
      POSTGRES_PASSWORD: previred.2024
      POSTGRES_DB: previred
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data:/data/postgres
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
      
  app:
    container_name: springboot-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/previred
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-previred}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-previred.2024}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  angular-app:
    container_name: angular-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Cambia 4200 a 80 si prefieres usar el puerto estándar para HTTP
    depends_on:
      - app # Asumiendo que tu aplicación Angular depende de tu backend
